services:
  aliro-scheduler:
    image: aliro-scheduler
    build:
      context: .
      dockerfile: Dockerfile
      target: aliro-scheduler
      args: 
        - CADABRA_VERSION=${CADABRA_VERSION}
        - GH_TOKEN=${GH_TOKEN}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - LOG_LEVEL=${LOG_LEVEL}
    env_file:
      - .env
    ports:
      - "${PORT}:9000"
